/*
  Warnings:

  - Made the column `user_id` on table `SystemLog` required. This step will fail if there are existing NULL values in that column.

*/
-- AlterTable
ALTER TABLE "FLEKSI" ALTER COLUMN "nomor_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "besar_pinjaman" DROP NOT NULL,
ALTER COLUMN "bunga_pinjaman" DROP NOT NULL,
ALTER COLUMN "jangka_waktu_pinjaman" DROP NOT NULL,
ALTER COLUMN "angsuran_pinjaman" DROP NOT NULL,
ALTER COLUMN "tanggal_angsuran_pertama" DROP NOT NULL,
ALTER COLUMN "hari_pembayaran_angsuran" DROP NOT NULL,
ALTER COLUMN "tanggal_pencairan" DROP NOT NULL,
ALTER COLUMN "nomor_rekening_pinjaman" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "nomor_surat_pernyataan_jaminan" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "alamat_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "barang_jaminan_lainnya" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan_jaminan" DROP NOT NULL,
ALTER COLUMN "nama_penjamin_hubungan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "FleksiBarangElektronik" ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tipe" DROP NOT NULL,
ALTER COLUMN "harga" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "FleksiBarangFurniture" ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tipe" DROP NOT NULL,
ALTER COLUMN "harga" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KAR" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_persetujuan_kredit" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "nominal" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_kendaraan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "hubungan_debitur_penjamin" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "utang_atas_kredit_sebesar" DROP NOT NULL,
ALTER COLUMN "tenggat_mengangsur_tiap_bulan" DROP NOT NULL,
ALTER COLUMN "nilai_mengangsur" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "biaya_provisi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_materai_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_jiwa_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_notaris_sebesar" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pemotongan_gaji" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KEF" ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "telah_mendapat_persetujuan" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "bertempat_tinggal_dengan" DROP NOT NULL,
ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "nama_toko" DROP NOT NULL,
ALTER COLUMN "alamat_toko" DROP NOT NULL,
ALTER COLUMN "harga_barang" DROP NOT NULL,
ALTER COLUMN "bunga_pinjaman" DROP NOT NULL,
ALTER COLUMN "total_pinjaman" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "tanggal_angsuran_berakhir" DROP NOT NULL,
ALTER COLUMN "tenggat_mengangsur_pada" DROP NOT NULL,
ALTER COLUMN "tanggal_angsuran_pertama" DROP NOT NULL,
ALTER COLUMN "nilai_mengangsur" DROP NOT NULL,
ALTER COLUMN "biaya_provisi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_materai_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_fidusia_sebesar" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "harga_jaminan" DROP NOT NULL,
ALTER COLUMN "hari_pembuatan_surat" DROP NOT NULL,
ALTER COLUMN "jenis_kelamin_debitur" DROP NOT NULL,
ALTER COLUMN "nik_debitur" DROP NOT NULL,
ALTER COLUMN "no_hp_debitur" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_sewabeli" DROP NOT NULL,
ALTER COLUMN "total_harga_keseluruhan_barang" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KMM" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_persetujuan_kredit" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "nominal" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "biaya_administasi" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_kendaraan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "hubungan_debitur_penjamin" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "utang_atas_kredit" DROP NOT NULL,
ALTER COLUMN "tenggat_mengangsur_tiap_bulan" DROP NOT NULL,
ALTER COLUMN "nilai_mengangsur_tiap_bulan" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "biaya_provisi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_materai_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_jiwa_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_tlo" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_notaris_sebesar" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "nik_debitur" DROP NOT NULL,
ALTER COLUMN "jenis_kelamin_debitur" DROP NOT NULL,
ALTER COLUMN "harga_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KMS" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penawaran_kredit" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "tujuan" DROP NOT NULL,
ALTER COLUMN "plafond" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "alamat_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "telah_persetujuan_dari" DROP NOT NULL,
ALTER COLUMN "nama_penjamin_1" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin_1" DROP NOT NULL,
ALTER COLUMN "bertempat_sama_dengan" DROP NOT NULL,
ALTER COLUMN "debitur_adalah_pemilik_rekening" DROP NOT NULL,
ALTER COLUMN "melunasi_hutang_sebesar" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_tiap_bulan" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "nominal_angsuran" DROP NOT NULL,
ALTER COLUMN "biaya_provisi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi_sebesar" DROP NOT NULL,
ALTER COLUMN "nama_asuransi_jiwa" DROP NOT NULL,
ALTER COLUMN "waktu_asuransi_jiwa" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_jiwa_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_materai_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_notaris_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_jumlah" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan_1" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KMSM" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pemberian_kredit" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "nominal" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_kendaraan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "hubungan_debitur_penjamin" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "utang_atas_kredit" DROP NOT NULL,
ALTER COLUMN "tenggat_mengangsur_tanggal" DROP NOT NULL,
ALTER COLUMN "nilai_mengangsur" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "biaya_provisi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_materai" DROP NOT NULL,
ALTER COLUMN "waktu_asuransi_tlo" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_tlo" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_notaris" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "nik_debitur" DROP NOT NULL,
ALTER COLUMN "jenis_kelamin_debitur" DROP NOT NULL,
ALTER COLUMN "harga_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KRS" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_persetujuan_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan" DROP NOT NULL,
ALTER COLUMN "plafond" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "telah_persetujuan_dari" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "bertempat_tinggal_sama_dengan" DROP NOT NULL,
ALTER COLUMN "debitur_pemilik_rekening" DROP NOT NULL,
ALTER COLUMN "melunasi_hutang_sebesar" DROP NOT NULL,
ALTER COLUMN "jangka_waktu_angsuran" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_paling_lambat" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "nominal_angsuran" DROP NOT NULL,
ALTER COLUMN "biaya_provisi_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi_sebesar" DROP NOT NULL,
ALTER COLUMN "waktu_asuransi_jiwa" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_jiwa" DROP NOT NULL,
ALTER COLUMN "biaya_materai_sebesar" DROP NOT NULL,
ALTER COLUMN "biaya_jumlah" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_terima_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan_1" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KSM" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pemberian_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "nominal" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "provisi" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_kendaraan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "mendapat_persetujuan_dari" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_tinggal_sama_dengan" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "seluruh_hutang_sebesar" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_paling_lambat" DROP NOT NULL,
ALTER COLUMN "biaya_angsuran" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "biaya_materai" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi_tlo" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi" DROP NOT NULL,
ALTER COLUMN "biaya_notaris" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pengikatan_jaminan" DROP NOT NULL,
ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "nik_debitur" DROP NOT NULL,
ALTER COLUMN "jenis_kelamin_debitur" DROP NOT NULL,
ALTER COLUMN "harga_jaminan_saat_ini" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa" DROP NOT NULL,
ALTER COLUMN "tanggal_pencairan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan_2" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KSS" ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "plaford" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "alamat_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "persetujuan_dari" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tinggal_sama_dengan" DROP NOT NULL,
ALTER COLUMN "bunga_pinjaman" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan_kredit" DROP NOT NULL,
ALTER COLUMN "total_seluruh_pinjaman" DROP NOT NULL,
ALTER COLUMN "tanggal_angsuran_dimulai" DROP NOT NULL,
ALTER COLUMN "tanggal_angsuran_terakhir" DROP NOT NULL,
ALTER COLUMN "angsuran_tiap_bulan" DROP NOT NULL,
ALTER COLUMN "nominal_provisi" DROP NOT NULL,
ALTER COLUMN "nominal_administrasi" DROP NOT NULL,
ALTER COLUMN "nama_asuransi" DROP NOT NULL,
ALTER COLUMN "jangka_asuransi" DROP NOT NULL,
ALTER COLUMN "biaya_asuransi" DROP NOT NULL,
ALTER COLUMN "biaya_materai" DROP NOT NULL,
ALTER COLUMN "biaya_notaris" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "nama_shm" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "jumlah_bank_menyerahkan_uang" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit_1" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL;

-- AlterTable
ALTER TABLE "KSSM" ADD COLUMN     "submitted_at" TIMESTAMP(3),
ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "jabatan" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "alamat_rumah_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_usaha_debitur" DROP NOT NULL,
ALTER COLUMN "biaya_administrasi" DROP NOT NULL,
ALTER COLUMN "biaya_provisi" DROP NOT NULL,
ALTER COLUMN "detail_jaminan" DROP NOT NULL,
ALTER COLUMN "harga_jaminan" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "jangka_asuransi_tlo" DROP NOT NULL,
ALTER COLUMN "jangka_waktu" DROP NOT NULL,
ALTER COLUMN "jenis_kelamin_debitur" DROP NOT NULL,
ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "nik_debitur" DROP NOT NULL,
ALTER COLUMN "nilai_mengangsur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "nominal" DROP NOT NULL,
ALTER COLUMN "nominal_administrasi" DROP NOT NULL,
ALTER COLUMN "nominal_asuransi_jiwa" DROP NOT NULL,
ALTER COLUMN "nominal_asuransi_tlo" DROP NOT NULL,
ALTER COLUMN "nominal_materai" DROP NOT NULL,
ALTER COLUMN "nominal_notaris" DROP NOT NULL,
ALTER COLUMN "nominal_provisi" DROP NOT NULL,
ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "suku_bunga" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tenggat_mengangsur" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "tujuan_penggunaan" DROP NOT NULL,
ALTER COLUMN "utang_atas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_fasilitas_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_kendaraan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perintah_jalan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PINEK" ALTER COLUMN "nomor_surat" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "pekerjaan_debitur" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tempat_tinggal_debitur" DROP NOT NULL,
ALTER COLUMN "mendapat_persetujuan" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tempat_tinggal_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_pengajuan_kredit" DROP NOT NULL,
ALTER COLUMN "debitur_menerima_pinjaman" DROP NOT NULL,
ALTER COLUMN "dikenakan_bunga" DROP NOT NULL,
ALTER COLUMN "total_seluruh_hutang" DROP NOT NULL,
ALTER COLUMN "jangka_waktu_hutang" DROP NOT NULL,
ALTER COLUMN "mengangsur_paling_lambat" DROP NOT NULL,
ALTER COLUMN "pemotongan_gaji" DROP NOT NULL,
ALTER COLUMN "biaya" DROP NOT NULL,
ALTER COLUMN "total_biaya" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_dokumen_agunan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_kuasa_debet" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pemotongan_gaji" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_pertama" DROP NOT NULL,
ALTER COLUMN "tanggal_mengangsur_terakhir" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PROCIM" ALTER COLUMN "nomor_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "hari" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_perjanjian_kredit" DROP NOT NULL,
ALTER COLUMN "nama_debitur" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_debitur" DROP NOT NULL,
ALTER COLUMN "alamat_debitur" DROP NOT NULL,
ALTER COLUMN "no_ktp_debitur" DROP NOT NULL,
ALTER COLUMN "nominal_plafond" DROP NOT NULL,
ALTER COLUMN "suku_bunga_pinjaman" DROP NOT NULL,
ALTER COLUMN "jangka_waktu_pinjaman" DROP NOT NULL,
ALTER COLUMN "angsuran_pinjaman" DROP NOT NULL,
ALTER COLUMN "tanggal_angsuran_pertama" DROP NOT NULL,
ALTER COLUMN "hari_pembayaran_angsuran" DROP NOT NULL,
ALTER COLUMN "tanggal_pencairan" DROP NOT NULL,
ALTER COLUMN "nomor_rekening_pinjaman" DROP NOT NULL,
ALTER COLUMN "nama_penjamin" DROP NOT NULL,
ALTER COLUMN "nomor_surat_pernyataan_jaminan" DROP NOT NULL,
ALTER COLUMN "tempat_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "tanggal_lahir_penjamin" DROP NOT NULL,
ALTER COLUMN "alamat_penjamin" DROP NOT NULL,
ALTER COLUMN "no_ktp_penjamin" DROP NOT NULL,
ALTER COLUMN "barang_jaminan_lainnya" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_pernyataan_jaminan" DROP NOT NULL,
ALTER COLUMN "tanggal_surat_penyerahan_jaminan" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ProcimBarangElektronik" ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tipe" DROP NOT NULL,
ALTER COLUMN "harga" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ProcimBarangFurniture" ALTER COLUMN "nama_barang" DROP NOT NULL,
ALTER COLUMN "tipe" DROP NOT NULL,
ALTER COLUMN "harga" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SystemLog" ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "role" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL;
