import db from "../../config/db.js";
class KSMService {
    async getAll(){
        const datas = await db.KSM.findMany()
        return datas
    }

    async getById(id) {
        const data = await db.KSM.findUnique({
            where: {
                id: parseInt(id)
            }
        });
        return data;
    }

    async create({
        nama,
        jabatan,
        nama_debitur,
        alamat_usaha_debitur,
        alamat_rumah_debitur,
        tanggal_surat_perintah_jalan,
        tanggal_surat_pemberian_fasilitas_kredit,
        nomor_surat,
        nominal,
        tujuan_penggunaan,
        suku_bunga,
        provisi,
        jangka_waktu,
        detail_jaminan,
        pekerjaan_debitur,
        tanggal_surat_kuasa_debet,
        tempat_lahir_debitur,
        tanggal_lahir_debitur,
        no_ktp_debitur,
        tanggal_surat_kuasa_kendaraan,
        hari,
        tanggal_surat_perjanjian_kredit,
        mendapat_persetujuan_dari,
        nama_penjamin,
        tempat_lahir_penjamin,
        tanggal_lahir_penjamin,
        tempat_tinggal_sama_dengan,
        no_ktp_penjamin,
        seluruh_hutang_sebesar,
        tanggal_mengangsur_paling_lambat,
        biaya_angsuran,
        tanggal_mengangsur_pertama,
        tanggal_mengangsur_terakhir,
        biaya_provisi,
        biaya_materai,
        biaya_asuransi,
        biaya_asuransi_tlo,
        biaya_administrasi,
        biaya_notaris,
        total_biaya,
        tanggal_surat_pengikatan_jaminan,
        nama_barang,
        tanggal_surat_penyerahan_jaminan,
        tanggal_surat_fasilitas_kredit,
        tanggal_surat_pernyataan,
        nik_debitur,
        jenis_kelamin_debitur,
        harga_jaminan_saat_ini,
        tanggal_surat_kuasa,
        tanggal_pencairan,
        tanggal_surat_pernyataan_2,
        submitted_at,
    }){
        const newKSM = await db.KSM.create({
            data:{
                nama:nama,
                jabatan:jabatan,
                nama_debitur:nama_debitur,
                alamat_usaha_debitur:alamat_usaha_debitur,
                alamat_rumah_debitur:alamat_rumah_debitur,
                tanggal_surat_perintah_jalan:tanggal_surat_perintah_jalan?new Date(tanggal_surat_perintah_jalan):null,
                tanggal_surat_pemberian_fasilitas_kredit:tanggal_surat_pemberian_fasilitas_kredit?new Date(tanggal_surat_pemberian_fasilitas_kredit):null,
                nomor_surat:nomor_surat,
                nominal:nominal,
                tujuan_penggunaan:tujuan_penggunaan,
                suku_bunga:suku_bunga,
                provisi:provisi,
                jangka_waktu:jangka_waktu,
                detail_jaminan:detail_jaminan,
                pekerjaan_debitur:pekerjaan_debitur,
                tanggal_surat_kuasa_debet:tanggal_surat_kuasa_debet?new Date(tanggal_surat_kuasa_debet):null,
                tempat_lahir_debitur:tempat_lahir_debitur,
                tanggal_lahir_debitur:tanggal_lahir_debitur?new Date(tanggal_lahir_debitur):null,
                no_ktp_debitur:no_ktp_debitur,
                tanggal_surat_kuasa_kendaraan:tanggal_surat_kuasa_kendaraan?new Date(tanggal_surat_kuasa_kendaraan):null,
                hari:hari,
                tanggal_surat_perjanjian_kredit:tanggal_surat_perjanjian_kredit?new Date(tanggal_surat_perjanjian_kredit):null,
                mendapat_persetujuan_dari:mendapat_persetujuan_dari,
                nama_penjamin:nama_penjamin,
                tempat_lahir_penjamin:tempat_lahir_penjamin,
                tanggal_lahir_penjamin:tanggal_lahir_penjamin?new Date(tanggal_lahir_penjamin):null,
                tempat_tinggal_sama_dengan:tempat_tinggal_sama_dengan,
                no_ktp_penjamin:no_ktp_penjamin,
                seluruh_hutang_sebesar:seluruh_hutang_sebesar,
                tanggal_mengangsur_paling_lambat:tanggal_mengangsur_paling_lambat,
                biaya_angsuran:biaya_angsuran,
                tanggal_mengangsur_pertama:tanggal_mengangsur_pertama?new Date(tanggal_mengangsur_pertama):null,
                tanggal_mengangsur_terakhir:tanggal_mengangsur_terakhir?new Date(tanggal_mengangsur_terakhir):null,
                biaya_provisi:biaya_provisi,
                biaya_materai:biaya_materai,
                biaya_asuransi:biaya_asuransi,
                biaya_asuransi_tlo:biaya_asuransi_tlo,
                biaya_administrasi:biaya_administrasi,
                biaya_notaris:biaya_notaris,
                total_biaya:total_biaya,
                tanggal_surat_pengikatan_jaminan:tanggal_surat_pengikatan_jaminan?new Date(tanggal_surat_pengikatan_jaminan):null,
                nama_barang:nama_barang,
                tanggal_surat_penyerahan_jaminan:tanggal_surat_penyerahan_jaminan?new Date(tanggal_surat_penyerahan_jaminan):null,
                tanggal_surat_fasilitas_kredit:tanggal_surat_fasilitas_kredit?new Date(tanggal_surat_fasilitas_kredit):null,
                tanggal_surat_pernyataan:tanggal_surat_pernyataan?new Date(tanggal_surat_pernyataan):null,
                nik_debitur:nik_debitur,
                jenis_kelamin_debitur:jenis_kelamin_debitur,
                harga_jaminan_saat_ini:harga_jaminan_saat_ini,
                tanggal_surat_kuasa:tanggal_surat_kuasa?new Date(tanggal_surat_kuasa):null,
                tanggal_pencairan:tanggal_pencairan?new Date(tanggal_pencairan):null,
                tanggal_surat_pernyataan_2:tanggal_surat_pernyataan_2?new Date(tanggal_surat_pernyataan_2):null,
                submitted_at:new Date()
            }
        })
        if (!newKSM) {
            throw new Error("Create KSM failed");
        }
        return newKSM
    }

    async update(id, {
        nama,
        jabatan,
        nama_debitur,
        alamat_usaha_debitur,
        alamat_rumah_debitur,
        tanggal_surat_perintah_jalan,
        tanggal_surat_pemberian_fasilitas_kredit,
        nomor_surat,
        nominal,
        tujuan_penggunaan,
        suku_bunga,
        provisi,
        jangka_waktu,
        detail_jaminan,
        pekerjaan_debitur,
        tanggal_surat_kuasa_debet,
        tempat_lahir_debitur,
        tanggal_lahir_debitur,
        no_ktp_debitur,
        tanggal_surat_kuasa_kendaraan,
        hari,
        tanggal_surat_perjanjian_kredit,
        mendapat_persetujuan_dari,
        nama_penjamin,
        tempat_lahir_penjamin,
        tanggal_lahir_penjamin,
        tempat_tinggal_sama_dengan,
        no_ktp_penjamin,
        seluruh_hutang_sebesar,
        tanggal_mengangsur_paling_lambat,
        biaya_angsuran,
        tanggal_mengangsur_pertama,
        tanggal_mengangsur_terakhir,
        biaya_provisi,
        biaya_materai,
        biaya_asuransi,
        biaya_asuransi_tlo,
        biaya_administrasi,
        biaya_notaris,
        total_biaya,
        tanggal_surat_pengikatan_jaminan,
        nama_barang,
        tanggal_surat_penyerahan_jaminan,
        tanggal_surat_fasilitas_kredit,
        tanggal_surat_pernyataan,
        nik_debitur,
        jenis_kelamin_debitur,
        harga_jaminan_saat_ini,
        tanggal_surat_kuasa,
        tanggal_pencairan,
        tanggal_surat_pernyataan_2,
        status,
        submitted_at,
    }) {
        const updatedKSM = await db.KSM.update({
            where: {
                id: parseInt(id)
            },
            data: {
                nama:nama,
                jabatan:jabatan,
                nama_debitur:nama_debitur,
                alamat_usaha_debitur:alamat_usaha_debitur,
                alamat_rumah_debitur:alamat_rumah_debitur,
                tanggal_surat_perintah_jalan:tanggal_surat_perintah_jalan?new Date(tanggal_surat_perintah_jalan):null,
                tanggal_surat_pemberian_fasilitas_kredit:tanggal_surat_pemberian_fasilitas_kredit?new Date(tanggal_surat_pemberian_fasilitas_kredit):null,
                nomor_surat:nomor_surat,
                nominal:nominal,
                tujuan_penggunaan:tujuan_penggunaan,
                suku_bunga:suku_bunga,
                provisi:provisi,
                jangka_waktu:jangka_waktu,
                detail_jaminan:detail_jaminan,
                pekerjaan_debitur:pekerjaan_debitur,
                tanggal_surat_kuasa_debet:tanggal_surat_kuasa_debet?new Date(tanggal_surat_kuasa_debet):null,
                tempat_lahir_debitur:tempat_lahir_debitur,
                tanggal_lahir_debitur:tanggal_lahir_debitur?new Date(tanggal_lahir_debitur):null,
                no_ktp_debitur:no_ktp_debitur,
                tanggal_surat_kuasa_kendaraan:tanggal_surat_kuasa_kendaraan?new Date(tanggal_surat_kuasa_kendaraan):null,
                hari:hari,
                tanggal_surat_perjanjian_kredit:tanggal_surat_perjanjian_kredit?new Date(tanggal_surat_perjanjian_kredit):null,
                mendapat_persetujuan_dari:mendapat_persetujuan_dari,
                nama_penjamin:nama_penjamin,
                tempat_lahir_penjamin:tempat_lahir_penjamin,
                tanggal_lahir_penjamin:tanggal_lahir_penjamin?new Date(tanggal_lahir_penjamin):null,
                tempat_tinggal_sama_dengan:tempat_tinggal_sama_dengan,
                no_ktp_penjamin:no_ktp_penjamin,
                seluruh_hutang_sebesar:seluruh_hutang_sebesar,
                tanggal_mengangsur_paling_lambat:tanggal_mengangsur_paling_lambat,
                biaya_angsuran:biaya_angsuran,
                tanggal_mengangsur_pertama:tanggal_mengangsur_pertama?new Date(tanggal_mengangsur_pertama):null,
                tanggal_mengangsur_terakhir:tanggal_mengangsur_terakhir?new Date(tanggal_mengangsur_terakhir):null,
                biaya_provisi:biaya_provisi,
                biaya_materai:biaya_materai,
                biaya_asuransi:biaya_asuransi,
                biaya_asuransi_tlo:biaya_asuransi_tlo,
                biaya_administrasi:biaya_administrasi,
                biaya_notaris:biaya_notaris,
                total_biaya:total_biaya,
                tanggal_surat_pengikatan_jaminan:tanggal_surat_pengikatan_jaminan?new Date(tanggal_surat_pengikatan_jaminan):null,
                nama_barang:nama_barang,
                tanggal_surat_penyerahan_jaminan:tanggal_surat_penyerahan_jaminan?new Date(tanggal_surat_penyerahan_jaminan):null,
                tanggal_surat_fasilitas_kredit:tanggal_surat_fasilitas_kredit?new Date(tanggal_surat_fasilitas_kredit):null,
                tanggal_surat_pernyataan:tanggal_surat_pernyataan?new Date(tanggal_surat_pernyataan):null,
                nik_debitur:nik_debitur,
                jenis_kelamin_debitur:jenis_kelamin_debitur,
                harga_jaminan_saat_ini:harga_jaminan_saat_ini,
                tanggal_surat_kuasa:tanggal_surat_kuasa?new Date(tanggal_surat_kuasa):null,
                tanggal_pencairan:tanggal_pencairan?new Date(tanggal_pencairan):null,
                tanggal_surat_pernyataan_2:tanggal_surat_pernyataan_2?new Date(tanggal_surat_pernyataan_2):null,
                status:status,
                updated_at: new Date(),
                submitted_at
            }
        });

        return updatedKSM;
    }
}

export default new KSMService();