import db from "../../config/db.js";
class KMMService {
    async getAll(){
        const datas = await db.KMM.findMany()
        return datas
    }
    async create({
        nama,
        jabatan,
        nama_debitur,
        alamat_usaha_debitur,
        alamat_rumah_debitur,
        tanggal_surat_perintah_jalan,
        tanggal_surat_persetujuan_kredit,
        nomor_surat,
        nominal,
        tujuan_penggunaan,
        suku_bunga,
        jangka_waktu,
        biaya_provisi,
        biaya_administasi,
        detail_jaminan,
        pekerjaan_debitur,
        tanggal_surat_kuasa_debet,
        tanggal_lahir_debitur,
        no_ktp_debitur,
        tanggal_surat_kuasa_kendaraan,
        hari,
        tanggal_surat_perjanjian_kredit,
        tempat_lahir_debitur,
        hubungan_debitur_penjamin,
        nama_penjamin,
        tempat_lahir_penjamin,
        tanggal_lahir_penjamin,
        no_ktp_penjamin,
        utang_atas_kredit,
        tenggat_mengangsur_tiap_bulan,
        nilai_mengangsur_tiap_bulan,
        tanggal_mengangsur_pertama,
        tanggal_mengangsur_terakhir,
        biaya_provisi_sebesar,
        biaya_materai_sebesar,
        biaya_asuransi_jiwa_sebesar,
        biaya_asuransi_tlo,
        biaya_administrasi_sebesar,
        biaya_notaris_sebesar,
        total_biaya,
        nama_barang,
        tanggal_surat_penyerahan_jaminan,
        tanggal_surat_fasilitas_kredit,
        tanggal_surat_pernyataan,
        nik_debitur,
        jenis_kelamin_debitur,
        harga_jaminan,
        tanggal_surat_kuasa
    }){
        const newKMM = await db.KMM.create({
            data:{
            nama:nama,
            jabatan:jabatan,
            nama_debitur:nama_debitur,
            alamat_usaha_debitur:alamat_usaha_debitur,
            alamat_rumah_debitur:alamat_rumah_debitur,
            tanggal_surat_perintah_jalan:new Date(tanggal_surat_perintah_jalan).toISOString(),
            tanggal_surat_persetujuan_kredit:new Date(tanggal_surat_persetujuan_kredit).toISOString(),
            nomor_surat:nomor_surat,
            nominal:nominal,
            tujuan_penggunaan:tujuan_penggunaan,
            suku_bunga:suku_bunga,
            jangka_waktu:jangka_waktu,
            biaya_provisi:biaya_provisi,
            biaya_administasi:biaya_administasi,
            detail_jaminan:detail_jaminan,
            pekerjaan_debitur:pekerjaan_debitur,
            tanggal_surat_kuasa_debet:new Date(tanggal_surat_kuasa_debet).toISOString(),
            tanggal_lahir_debitur:new Date(tanggal_lahir_debitur).toISOString(),
            no_ktp_debitur:no_ktp_debitur,
            tanggal_surat_kuasa_kendaraan:new Date(tanggal_surat_kuasa_kendaraan).toISOString(),
            hari:hari,
            tanggal_surat_perjanjian_kredit:new Date(tanggal_surat_perjanjian_kredit).toISOString(),
            tempat_lahir_debitur:tempat_lahir_debitur,
            hubungan_debitur_penjamin:hubungan_debitur_penjamin,
            nama_penjamin:nama_penjamin,
            tempat_lahir_penjamin:tempat_lahir_penjamin,
            tanggal_lahir_penjamin:new Date(tanggal_lahir_penjamin).toISOString(),
            no_ktp_penjamin:no_ktp_penjamin,
            utang_atas_kredit:utang_atas_kredit,
            tenggat_mengangsur_tiap_bulan:tenggat_mengangsur_tiap_bulan,
            nilai_mengangsur_tiap_bulan:nilai_mengangsur_tiap_bulan,
            tanggal_mengangsur_pertama:new Date(tanggal_mengangsur_pertama).toISOString(),
            tanggal_mengangsur_terakhir:new Date(tanggal_mengangsur_terakhir).toISOString(),
            biaya_provisi_sebesar:biaya_provisi_sebesar,
            biaya_materai_sebesar:biaya_materai_sebesar,
            biaya_asuransi_jiwa_sebesar:biaya_asuransi_jiwa_sebesar,
            biaya_asuransi_tlo:biaya_asuransi_tlo,
            biaya_administrasi_sebesar:biaya_administrasi_sebesar,
            biaya_notaris_sebesar:biaya_notaris_sebesar,
            total_biaya:total_biaya,
            nama_barang:nama_barang,
            tanggal_surat_penyerahan_jaminan:new Date(tanggal_surat_penyerahan_jaminan).toISOString(),
            tanggal_surat_fasilitas_kredit:new Date(tanggal_surat_fasilitas_kredit).toISOString(),
            tanggal_surat_pernyataan:new Date(tanggal_surat_pernyataan).toISOString(),
            nik_debitur:nik_debitur,
            jenis_kelamin_debitur:jenis_kelamin_debitur,
            harga_jaminan:harga_jaminan,
            tanggal_surat_kuasa:new Date(tanggal_surat_kuasa).toISOString()
            }
        })
        if (!newKMM) {
            throw new Error("Create KMM failed");
        }
        return newKMM
    }
}

export default new KMMService();