// prisma/seed.ts
import { PrismaClient } from "../generated/prisma/index.js";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

console.log(Object.keys(prisma));

async function main() {
  const user = await prisma.user.create({
    data: {
      username: "adminSuper",
      password: await bcrypt.hash("Password123.", await bcrypt.genSalt(10)),
      role: "PIC",
    },
  });

  await prisma.kSSM.create({
    data: {
      nomor_surat: "KSSM-001",
      tanggal_surat_permohonan_kredit: new Date("2025-01-01"),
      tanggal_surat_persetujuan_kredit: new Date("2025-01-05"),
      nama: "MUHAMAD JAMALUDIN",
      jabatan: "AREA MANAGER",
      nama_debitur: "DEDE SUTRIS",
      nik_debitur: "3209061103910008",
      status_debitur: "Kawin",
      hubungan_debitur_penjamin: "Suami",
      alamat_usaha_debitur: "DUSUN 03 RT 01 RW 06 DESA KARANGMEKAR KAB CIREBON",
      alamat_rumah_debitur: "DUSUN 03 RT 01 RW 06 DESA KARANGMEKAR KAB CIREBON",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1990-05-15"),
      pekerjaan_debitur: "BURUH HARIAN LEPAS",
      jenis_kelamin_debitur: "Laki-Laki",
      nama_penjamin: "ADE SURYANI",
      nik_penjamin: "6543210987654321",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1985-08-22"),
      hubungan_penjamin_debitur: "Istri",
      alamat_rumah_penjamin:
        "DUSUN 03 RT 01 RW 06 DESA KARANGMEKAR KAB CIREBON",
      nama_barang: "KENDARAAN BERMOTOR RODA DUA",
      no_bpkb: "M-00718385",
      harga_barang: 15000000,
      detail_jaminan:
        "BPKB NOMOR P-08011239 AN ADE SURYANI ALAMAT JAMINAN DESA KARANGMEKAR RT 01/06 KEC KARANGSEMBUNG KAB CIREBON. MEREK/TYPE HONDA C1M02N41L0 A/T TAHUN 2019 WARNA HITAM MERAH ISI SILINDER 110 CC NO RANGKA MH1JM611XKK044768 NO MESIN JM61F1044943 ",
      nominal_pinjaman: 10000000,
      bunga_pinjaman: 25.8,
      jangka_waktu: 12,
      tujuan_penggunaan: "TAMBAHAN MODAL",
      nominal_angsuran: 950000,
      tanggal_angsuran_pertama: new Date("2025-02-01"),
      tanggal_angsuran_terakhir: new Date("2026-01-01"),
      hutang_keseluruhan: 11400000,
      tenggat_angsuran: 30,
      provisi_persen: 1.0,
      provisi_nominal: 100000,
      administrasi_persen: 0.5,
      administrasi_nominal: 50000,
      materai_nominal: 10000,
      asuransi_jiwa_nominal: 30000,
      asuransi_tlo_nominal: 25000,
      notaris_nominal: 150000,
      total_biaya: 365000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kSS.create({
    data: {
      nomor_surat: "KSS-001",
      tanggal_surat_permohonan_kredit: new Date("2025-03-01"),
      tanggal_surat_persetujuan_kredit: new Date("2025-03-05"),
      nama: "SRI HANDAYANI",
      jabatan: "KEPALA CABANG",
      nama_debitur: "TATANG SUPRATMAN",
      nik_debitur: "3210010202800002",
      status_debitur: "Kawin",
      hubungan_debitur_penjamin: "Istri",
      alamat_usaha_debitur: "JL. RAYA KUNINGAN KM 3 NO 10",
      alamat_rumah_debitur: "PERUM GRIYA CIREBON INDAH BLOK B2 NO 6",
      pekerjaan_debitur: "PENGUSAHA",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1980-02-02"),
      nama_penjamin: "RINA SUSANTI",
      nik_penjamin: "3210010202830001",
      alamat_rumah_penjamin: "PERUM GRIYA CIREBON INDAH BLOK B2 NO 6",
      tempat_lahir_penjamin: "CIREBON",
      hubungan_penjamin_debitur: "Istri",
      tanggal_lahir_penjamin: new Date("1983-02-02"),
      nama_shm: "TATANG SUPRATMAN",
      nik_shm: "3210010202800002",
      alamat_shm: "JL. KESAMBI DALAM NO 4",
      detail_jaminan: "SHM NO 1123 AN. TATANG SUPRATMAN, LUAS 150M2, CIREBON",
      nominal_pinjaman: 20000000,
      bunga_pinjaman: 18,
      jangka_waktu: 24,
      tujuan_penggunaan: "MODAL USAHA",
      nominal_angsuran: 950000,
      tanggal_angsuran_dimulai: new Date("2025-04-01"),
      tanggal_angsuran_terakhir: new Date("2027-03-01"),
      hutang_keseluruhan: 22800000,
      provisi_persen: 1,
      administrasi_persen: 0.5,
      provisi_nominal: 200000,
      administrasi_nominal: 100000,
      nama_asuransi: "ASURANSI BERSAMA",
      asuransi_nominal: 150000,
      materai_nominal: 10000,
      notaris_nominal: 250000,
      total_biaya: 710000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.pINEK.create({
    data: {
      nomor_surat: "PINEK-001",
      tanggal_surat_permohonan_kredit: new Date("2025-05-10"),
      tanggal_surat_persetujuan_kredit: new Date("2025-05-12"),
      nama_debitur: "SARI WULANDARI",
      nik_debitur: "3276016204930003",
      status_debitur: "Belum Kawin",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1993-04-20"),
      alamat_rumah_debitur: "PERUM GUNUNG SARI BLOK C NO 5",
      pekerjaan_debitur: "KARYAWATI",
      nama_penjamin: "DEDI SUPRIADI",
      nik_penjamin: "3276016204800002",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1980-04-12"),
      hubungan_penjamin_debitur: "Kakak",
      alamat_rumah_penjamin: "PERUM GUNUNG SARI BLOK C NO 5",
      nama_barang: "IJAZAH S1 + BPJS KESEHATAN",
      detail_jaminan: "IJAZAH ORIGINAL + BPJS KESEHATAN AKTIF",
      nominal_pinjaman: 5000000,
      bunga_pinjaman: 20,
      jangka_waktu: 10,
      nominal_angsuran: 550000,
      tanggal_angsuran_pertama: new Date("2025-06-01"),
      tanggal_angsuran_terakhir: new Date("2026-03-01"),
      hutang_keseluruhan: 5500000,
      tenggat_angsuran: 1,
      rekening_pinjaman: "112001002999",
      tujuan_penggunaan: "PENDIDIKAN",
      provisi_persen: 1,
      provisi_nominal: 50000,
      nama_asuransi: "ASURANSI PENDIDIKAN",
      asuransi_jiwa_nominal: 25000,
      materai_nominal: 10000,
      total_biaya: 85000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.fLEKSI.create({
    data: {
      nomor_surat: "FLEKSI-001",
      tanggal_surat_persetujuan_kredit: new Date("2025-07-01"),
      nama_debitur: "NURUL AINI",
      status_debitur: "Kawin",
      jenis_kelamin_debitur: "Perempuan",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1992-08-10"),
      alamat_rumah_debitur: "PERUM RANCAEKER BLOK D5 NO 8",
      nik_debitur: "3276016208920004",
      nama_penjamin: "AGUS SURYANA",
      nik_penjamin: "3276016208880003",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1988-09-18"),
      hubungan_penjamin_debitur: "Suami",
      alamat_rumah_penjamin: "PERUM RANCAEKER BLOK D5 NO 8",
      nominal_pinjaman: 6000000,
      bunga_pinjaman: 20.0,
      jangka_waktu: 10,
      tujuan_penggunaan: "PEMBELIAN PERABOT RUMAH",
      rekening_pinjaman: "112001002776",
      nominal_angsuran: 660000,
      tanggal_angsuran_pertama: new Date("2025-08-01"),
      tenggat_angsuran: "Senin",
      submitted_at: new Date(),
      userID: user.id,
      barang_elektronik: {
        createMany: {
          data: [
            {
              nama_barang: "TV LED",
              tipe: "SAMSUNG 43 INCH",
              harga: 3000000,
            },
          ],
        },
      },
      barang_furniture: {
        createMany: {
          data: [
            {
              nama_barang: "LEMARI BAJU",
              tipe: "3 PINTU MINIMALIS",
              harga: 2000000,
            },
          ],
        },
      },
      barang_jaminan_lainnya: {
        createMany: {
          data: [
            {
              nama_barang: "KARPET PERSIA",
            },
          ],
        },
      },
    },
  });

  await prisma.pROCIM.create({
    data: {
      nomor_surat: "PROCIM-001",
      tanggal_surat_persetujuan_kredit: new Date("2025-01-15"),
      nama_debitur: "NUR KHOLIS",
      nik_debitur: "3210112301890007",
      status_debitur: "Kawin",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1989-03-12"),
      alamat_rumah_debitur: "DESA KERTAWINANGUN KEC MANDIRANCAN KAB KUNINGAN",
      nama_penjamin: "MIRA WULANDARI",
      nik_penjamin: "3210112301900002",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1990-03-22"),
      alamat_rumah_penjamin: "DESA KERTAWINANGUN KEC MANDIRANCAN KAB KUNINGAN",
      nominal_pinjaman: 8000000,
      bunga_pinjaman: 18.5,
      jangka_waktu: 10,
      rekening_pinjaman: "112001002110",
      nominal_angsuran: 870000,
      tanggal_angsuran_pertama: new Date("2025-02-15"),
      tenggat_angsuran: "Senin",
      userID: user.id,
      submitted_at: new Date(),
      barang_elektronik: {
        createMany: {
          data: [
            {
              nama_barang: "KULKAS",
              tipe: "LG SMART 2PINTU",
              harga: 3000000,
            },
          ],
        },
      },
      barang_furniture: {
        createMany: {
          data: [
            {
              nama_barang: "SOFA",
              tipe: "L SHAPE MODERN",
              harga: 2500000,
            },
          ],
        },
      },
      barang_jaminan_lainnya: {
        createMany: {
          data: [
            {
              nama_barang: "SEPEDA LISTRIK",
            },
          ],
        },
      },
    },
  });

  await prisma.kSM.create({
    data: {
      administrasi_nominal: 50000,
      administrasi_persen: 0.5,
      alamat_rumah_debitur: "DESA SINDANGJAWA BLOK KARANGANYAR RT 01 RW 02",
      alamat_usaha_debitur: "DESA SINDANGJAWA BLOK KARANGANYAR RT 01 RW 02",
      asuransi_nominal: 0,
      asuransi_tlo_nominal: 0,
      bunga_pinjaman: 24,
      detail_jaminan: "DESA SINDANGJAWA BLOK KARANGANYAR RT 01 RW 02",
      harga_barang: 0,
      hubungan_debitur_penjamin: "Suami",
      hubungan_penjamin_debitur: "Istri",
      hutang_keseluruhan: 11400000,
      jabatan: "Area Manager ",
      jangka_waktu: 12,
      jenis_kelamin_debitur: "Laki-laki",
      materai_nominal: 10000,
      nama: "Budiono Sudarmono",
      nama_barang: "Vario",
      nama_debitur: "ROFIUDIN",
      nama_penjamin: "SRI KURNIA",
      nik_debitur: "3210122301890001",
      nik_penjamin: "3210122301930002",
      no_bpkb: "N-20204567",
      nominal_angsuran: 950000,
      nominal_pinjaman: 10000000,
      nomor_surat: "001100.2/1",
      notaris_nominal: 0,
      pekerjaan_debitur: "PEDAGANG",
      provisi_nominal: 100000,
      provisi_persen: 1,
      status_debitur: "Kawin",
      submitted_at: new Date(),
      tanggal_angsuran_pertama: new Date("2025-05-01"),
      tanggal_angsuran_terakhir: new Date("2025-05-01"),
      tanggal_lahir_debitur: new Date(),
      tanggal_lahir_penjamin: new Date(),
      tanggal_surat_permohonan_kredit: new Date(),
      tanggal_surat_persetujuan_kredit: new Date(),
      tempat_lahir_debitur: "CIREBON",
      tempat_lahir_penjamin: "CIREBON",
      tenggat_angsuran: 10,
      total_biaya: 160000,
      tujuan_penggunaan: "TAMBAHAN MODAL USAHA",
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kMSM.create({
    data: {
      nomor_surat: "KMSM-001",
      tanggal_surat_permohonan_kredit: new Date("2025-04-01"),
      tanggal_surat_persetujuan_kredit: new Date("2025-04-05"),
      nama: "RENDI MAULANA",
      jabatan: "ACCOUNT OFFICER",
      nama_debitur: "RUDI SANTOSA",
      status_debitur: "Kawin",
      hubungan_debitur_penjamin: "Suami",
      jenis_kelamin_debitur: "Laki-Laki",
      nik_debitur: "3209111201930003",
      tempat_lahir_debitur: "MAJALENGKA",
      tanggal_lahir_debitur: new Date("1993-12-12"),
      alamat_usaha_debitur: "DESA RAJAGALUH WETAN RT 02 RW 01",
      alamat_rumah_debitur: "DESA RAJAGALUH WETAN RT 02 RW 01",
      pekerjaan_debitur: "TUKANG LAS",
      nama_penjamin: "SITI AMINAH",
      tempat_lahir_penjamin: "MAJALENGKA",
      tanggal_lahir_penjamin: new Date("1995-06-30"),
      nik_penjamin: "3209113006950004",
      hubungan_penjamin_debitur: "Istri",
      nama_barang: "SEPEDA MOTOR HONDA",
      harga_barang: 14000000,
      no_bpkb: "BPKB-987654",
      detail_jaminan:
        "BPKB NO. BPKB-987654 AN. SITI AMINAH, MERK HONDA VARIO 125 TAHUN 2021, WARNA HITAM, NO. RANGKA MH1JF5124MK001234, NO. MESIN JF51E-1001234",
      nominal_pinjaman: 10000000,
      bunga_pinjaman: 18.5,
      jangka_waktu: 12,
      tujuan_penggunaan: "MODAL KERJA",
      nominal_angsuran: 925000,
      tanggal_angsuran_pertama: new Date("2025-05-01"),
      tanggal_angsuran_terakhir: new Date("2026-04-01"),
      hutang_keseluruhan: 11100000,
      tenggat_angsuran: 1,
      provisi_persen: 1.0,
      provisi_nominal: 100000,
      administrasi_persen: 0.5,
      administrasi_nominal: 50000,
      materai_nominal: 10000,
      asuransi_tlo_nominal: 20000,
      notaris_nominal: 100000,
      total_biaya: 280000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kRS.create({
    data: {
      nomor_surat: "KRS-001",
      tanggal_surat_permohonan_kredit: new Date("2025-03-10"),
      tanggal_surat_persetujuan_kredit: new Date("2025-03-15"),
      nama: "AGUS SANTOSO",
      jabatan: "ACCOUNT OFFICER",
      nama_debitur: "BUDI PRATAMA",
      nik_debitur: "3210041202850005",
      status_debitur: "Kawin",
      hubungan_debitur_penjamin: "Suami",
      jenis_kelamin_debitur: "Laki-Laki",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1985-02-12"),
      alamat_usaha_debitur: "JL. PELABUHAN NO. 10 CIREBON",
      alamat_rumah_debitur: "JL. PELABUHAN NO. 10 CIREBON",
      pekerjaan_debitur: "PEDAGANG KELONTONG",
      nama_penjamin: "NINA MARLINA",
      nik_penjamin: "3210042506850006",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1985-06-25"),
      hubungan_penjamin_debitur: "Istri",
      nama_shm: "BUDI PRATAMA",
      nik_shm: "3210041202850005",
      alamat_shm: "JL. PELABUHAN NO. 10 CIREBON",
      detail_jaminan:
        "SHM No. 1234567 atas nama BUDI PRATAMA, Luas 120 m², Desa Citemu, Kec. Mundu, Kab. Cirebon",
      nominal_pinjaman: 20000000,
      bunga_pinjaman: 18.0,
      jangka_waktu: 18,
      tujuan_penggunaan: "RENOVASI RUMAH",
      nominal_angsuran: 1250000,
      tanggal_angsuran_pertama: new Date("2025-04-01"),
      tanggal_angsuran_terakhir: new Date("2026-09-01"),
      hutang_keseluruhan: 22500000,
      tenggat_angsuran: 1,
      provisi_persen: 1.0,
      administrasi_persen: 0.5,
      provisi_nominal: 200000,
      administrasi_nominal: 100000,
      nama_asuransi: "Asuransi Jaga Jiwa",
      asuransi_jiwa_nominal: 150000,
      materai_nominal: 10000,
      total_biaya: 460000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kMM.create({
    data: {
      nomor_surat: "KMM-001",
      tanggal_surat_permohonan_kredit: new Date("2025-04-10"),
      tanggal_surat_persetujuan_kredit: new Date("2025-04-15"),
      nama: "INDRA YULIANA",
      jabatan: "ACCOUNT OFFICER",
      nama_debitur: "JONI SUPRIADI",
      nik_debitur: "3210031504900006",
      status_debitur: "Kawin",
      hubungan_debitur_penjamin: "Suami",
      jenis_kelamin_debitur: "Laki-Laki",
      tanggal_lahir_debitur: new Date("1990-04-15"),
      tempat_lahir_debitur: "CIREBON",
      alamat_usaha_debitur: "JL. MAWAR NO. 45 CIREBON",
      alamat_rumah_debitur: "JL. MAWAR NO. 45 CIREBON",
      pekerjaan_debitur: "WIRAUSAHA",
      nama_penjamin: "SUSI MELANI",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1992-07-12"),
      nik_penjamin: "3210031207920003",
      hubungan_penjamin_debitur: "Istri",
      nama_barang: "MOBIL TOYOTA AVANZA",
      harga_barang: 120000000,
      no_bpkb: "BPKB-AVZ-789654",
      detail_jaminan:
        "BPKB MOBIL TOYOTA AVANZA, WARNA HITAM, TAHUN 2020, NOMOR RANGKA MHFCW123456789101, NOMOR MESIN CW456789",
      nominal_pinjaman: 80000000,
      bunga_pinjaman: 15.5,
      jangka_waktu: 24,
      tujuan_penggunaan: "MODAL USAHA",
      nominal_angsuran: 3850000,
      tanggal_angsuran_pertama: new Date("2025-05-01"),
      tanggal_angsuran_terakhir: new Date("2027-04-01"),
      hutang_keseluruhan: 92400000,
      tenggat_angsuran: 1,
      provisi_persen: 1.0,
      administrasi_persen: 0.5,
      provisi_nominal: 800000,
      administrasi_nominal: 400000,
      materai_nominal: 10000,
      asuransi_jiwa_nominal: 250000,
      nama_asuransi: "Asuransi Mobil Sejahtera",
      asuransi_tlo_nominal: 350000,
      notaris_nominal: 200000,
      total_biaya: 2010000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kMS.create({
    data: {
      nomor_surat: "KMS-001",
      tanggal_surat_permohonan_kredit: new Date("2025-02-10"),
      tanggal_surat_persetujuan_kredit: new Date("2025-02-15"),
      nama: "RINA WULANDARI",
      jabatan: "ACCOUNT OFFICER",
      nama_debitur: "AGUS SUPRIYANTO",
      status_debitur: "Kawin",
      alamat_usaha_debitur: "JL. MELATI NO. 88 CIREBON",
      alamat_rumah_debitur: "JL. MELATI NO. 88 CIREBON",
      nik_debitur: "3210030803820001",
      pekerjaan_debitur: "PENGUSAHA",
      hubungan_debitur_penjamin: "Suami",
      alamat_rumah_penjamin: "JL. MELATI NO. 88 CIREBON",
      nama_penjamin: "DESI NURMALASARI",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1985-06-22"),
      nik_penjamin: "3210032206850004",
      hubungan_penjamin_debitur: "Istri",
      nama_shm: "AGUS SUPRIYANTO",
      alamat_shm: "JL. MELATI NO. 88 CIREBON",
      nik_shm: "3210030803820001",
      detail_jaminan:
        "SHM NO. 123456789 ATAS NAMA AGUS SUPRIYANTO, LUAS 200M2, LOKASI JL. MELATI NO. 88 CIREBON",
      nominal_pinjaman: 75000000,
      tujuan_penggunaan: "MODAL PERLUASAN TOKO",
      jangka_waktu: 18,
      bunga_pinjaman: 14.0,
      tanggal_angsuran_terakhir: new Date("2026-08-01"),
      tenggat_angsuran: 1,
      tanggal_angsuran_pertama: new Date("2025-03-01"),
      nominal_angsuran: 4700000,
      hutang_keseluruhan: 84600000,
      provisi_persen: 1.0,
      provisi_nominal: 750000,
      administrasi_persen: 0.5,
      administrasi_nominal: 375000,
      materai_nominal: 10000,
      notaris_nominal: 200000,
      nama_asuransi_jiwa: "Asuransi Hidup Sejahtera",
      asuransi_jiwa_nominal: 300000,
      total_biaya: 1635000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kEF.create({
    data: {
      nomor_surat: "KEF-001",
      tanggal_surat_permohonan_kredit: new Date("2025-03-01"),
      tanggal_surat_persetujuan_kredit: new Date("2025-03-05"),
      nama_debitur: "NURUL HIKMAH",
      status_debitur: "Belum Kawin",
      nik_debitur: "3209051101990003",
      no_hp_debitur: "081234567890",
      jenis_kelamin_debitur: "Perempuan",
      hubungan_debitur_penjamin: "Anak",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1999-01-11"),
      nama_usaha_debitur: "Toko Sumber Berkah",
      alamat_usaha_debitur: "JL. RAYA PLOSOKEREP NO. 25 CIREBON",
      alamat_rumah_debitur: "JL. RAYA PLOSOKEREP NO. 25 CIREBON",
      pekerjaan_debitur: "PEDAGANG KELONTONG",
      nama_penjamin: "SUHARTI",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1970-04-15"),
      nik_penjamin: "3209051504700006",
      hubungan_penjamin_debitur: "Ibu",
      nama_barang: "KULKAS",
      merek_barang: "SHARP",
      tipe_barang: "SJ-195MD-SR",
      ukuran_barang: "185 Liter",
      warna_barang: "Silver",
      harga_barang: 3200000,
      detail_jaminan:
        "Kulkas SHARP 185L SJ-195MD-SR warna silver sebagai jaminan.",
      bunga_pinjaman: 18.0,
      jangka_waktu: 12,
      tanggal_angsuran_terakhir: new Date("2026-03-01"),
      tenggat_angsuran: 1,
      tanggal_angsuran_pertama: new Date("2025-04-01"),
      nominal_angsuran: 310000,
      hutang_keseluruhan: 3720000,
      provisi_persen: 1.0,
      provisi_nominal: 32000,
      administrasi_persen: 0.5,
      administrasi_nominal: 16000,
      materai_nominal: 10000,
      fidusia_nominal: 15000,
      total_biaya: 73000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  await prisma.kAR.create({
    data: {
      nomor_surat: "KAR-001",
      tanggal_surat_permohonan_kredit: new Date("2025-04-01"),
      tanggal_surat_persetujuan_kredit: new Date("2025-04-05"),
      nama: "BUDI SANTOSO",
      jabatan: "KOORDINATOR PEMASARAN",
      nama_debitur: "AGUS SETIAWAN",
      nik_debitur: "3209062204870002",
      status_debitur: "Kawin",
      hubungan_debitur_penjamin: "Suami",
      jenis_kelamin_debitur: "Laki-Laki",
      tempat_lahir_debitur: "CIREBON",
      tanggal_lahir_debitur: new Date("1987-04-22"),
      alamat_usaha_debitur: "JL. RAYA WERU KM. 8 CIREBON",
      alamat_rumah_debitur: "JL. RAYA WERU KM. 8 CIREBON",
      pekerjaan_debitur: "SOPIR TRUK",
      nama_penjamin: "DEWI LESTARI",
      nik_penjamin: "3209061205890005",
      tempat_lahir_penjamin: "CIREBON",
      tanggal_lahir_penjamin: new Date("1989-05-12"),
      hubungan_penjamin_debitur: "Istri",
      alamat_rumah_penjamin: "JL. RAYA WERU KM. 8 CIREBON",
      nama_barang: "HONDA BEAT CBS 2020",
      no_bpkb: "N-20204567",
      detail_jaminan:
        "BPKB MOTOR HONDA BEAT CBS TAHUN 2020 WARNA PUTIH BIRU, NO. RANGKA MH1JF5115LK023456, NO. MESIN JF51E1234567",
      nominal_pinjaman: 8000000,
      bunga_pinjaman: 22.5,
      jangka_waktu: 12,
      nominal_angsuran: 750000,
      tanggal_angsuran_pertama: new Date("2025-05-01"),
      tanggal_angsuran_terakhir: new Date("2026-04-01"),
      hutang_keseluruhan: 9000000,
      tenggat_angsuran: 1,
      provisi_persen: 1.0,
      administrasi_nominal: 40000,
      provisi_nominal: 80000,
      materai_nominal: 10000,
      asuransi_jiwa_nominal: 25000,
      nama_asuransi: "Asuransi Jiwa Sejahtera",
      notaris_nominal: 120000,
      total_biaya: 275000,
      submitted_at: new Date(),
      userID: user.id,
    },
  });

  console.log("✅ Seed data berhasil dibuat.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
